"""Add new scanner models

Revision ID: 207e09fa9595
Revises: 
Create Date: 2026-03-24 07:08:24.031493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207e09fa9595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphql_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('has_introspection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphql_endpoints_id'), 'graphql_endpoints', ['id'], unique=False)
    op.create_table('javascript_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('extracted_endpoints', sa.String(), nullable=True),
    sa.Column('extracted_parameters', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_javascript_files_id'), 'javascript_files', ['id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('extracted_from', sa.String(), nullable=True),
    sa.Column('secret_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.drop_index(op.f('ix_monitoring_targets_domain'), table_name='monitoring_targets')
    op.drop_index(op.f('ix_monitoring_targets_id'), table_name='monitoring_targets')
    op.drop_table('monitoring_targets')
    op.drop_index(op.f('ix_secret_findings_id'), table_name='secret_findings')
    op.drop_table('secret_findings')
    op.drop_index(op.f('ix_graphql_findings_id'), table_name='graphql_findings')
    op.drop_table('graphql_findings')
    op.drop_column('directories', 'source')
    op.drop_column('directories', 'url')
    op.drop_column('directories', 'status_code')
    op.drop_column('endpoints', 'technologies')
    op.drop_column('endpoints', 'hidden_parameters')
    op.drop_column('endpoints', 'host')
    op.drop_column('endpoints', 'path')
    op.drop_column('endpoints', 'source')
    op.drop_column('endpoints', 'content_type')
    op.drop_column('endpoints', 'discovered_from')
    op.drop_column('endpoints', 'is_graphql')
    op.drop_column('scans', 'completed_at')
    op.drop_column('scans', 'monitoring_target_id')
    op.drop_column('scans', 'summary')
    op.drop_column('scans', 'output_dir')
    op.drop_column('scans', 'graph_data')
    op.drop_column('scans', 'started_at')
    op.drop_column('scans', 'report_path')
    op.drop_column('subdomains', 'technologies')
    op.drop_column('subdomains', 'ip_address')
    op.drop_column('subdomains', 'title')
    op.drop_column('subdomains', 'source')
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'subscription_status')
    op.add_column('vulnerabilities', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('exposure_level', sa.String(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('manual_review_required', sa.Boolean(), nullable=True))
    op.drop_column('vulnerabilities', 'host')
    op.drop_column('vulnerabilities', 'raw_data')
    op.drop_column('vulnerabilities', 'evidence')
    op.drop_column('vulnerabilities', 'matched_at')
    op.drop_column('vulnerabilities', 'template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerabilities', sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vulnerabilities', sa.Column('matched_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vulnerabilities', sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vulnerabilities', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.add_column('vulnerabilities', sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vulnerabilities', 'manual_review_required')
    op.drop_column('vulnerabilities', 'priority')
    op.drop_column('vulnerabilities', 'exposure_level')
    op.drop_column('vulnerabilities', 'confidence')
    op.add_column('users', sa.Column('subscription_status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.VARCHAR(), server_default=sa.text("'Free user'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('users', 'subscription_tier')
    op.add_column('subdomains', sa.Column('source', sa.VARCHAR(), server_default=sa.text("'subfinder'::character varying"), autoincrement=False, nullable=True))
    op.add_column('subdomains', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subdomains', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subdomains', sa.Column('technologies', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('report_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('graph_data', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('output_dir', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('summary', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('monitoring_target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scans', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('is_graphql', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('discovered_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('source', sa.VARCHAR(), server_default=sa.text("'crawler'::character varying"), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('hidden_parameters', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('endpoints', sa.Column('technologies', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('directories', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('directories', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('directories', sa.Column('source', sa.VARCHAR(), server_default=sa.text("'ffuf'::character varying"), autoincrement=False, nullable=True))
    op.create_table('graphql_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('introspection_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('schema_types', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('graphql_findings_scan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('graphql_findings_pkey'))
    )
    op.create_index(op.f('ix_graphql_findings_id'), 'graphql_findings', ['id'], unique=False)
    op.create_table('secret_findings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_preview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_match', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('secret_findings_scan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('secret_findings_pkey'))
    )
    op.create_index(op.f('ix_secret_findings_id'), 'secret_findings', ['id'], unique=False)
    op.create_table('monitoring_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scan_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_diff', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('monitoring_targets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('monitoring_targets_pkey'))
    )
    op.create_index(op.f('ix_monitoring_targets_id'), 'monitoring_targets', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_targets_domain'), 'monitoring_targets', ['domain'], unique=False)
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_javascript_files_id'), table_name='javascript_files')
    op.drop_table('javascript_files')
    op.drop_index(op.f('ix_graphql_endpoints_id'), table_name='graphql_endpoints')
    op.drop_table('graphql_endpoints')
    # ### end Alembic commands ###
