"""Inventory and Diffing Phase 2

Revision ID: 3b49e145e95a
Revises: 207e09fa9595
Create Date: 2026-03-24 07:41:47.092310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b49e145e95a'
down_revision: Union[str, Sequence[str], None] = '207e09fa9595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('last_scan', sa.DateTime(), nullable=True),
    sa.Column('total_subdomains', sa.Integer(), nullable=True),
    sa.Column('total_endpoints', sa.Integer(), nullable=True),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('last_change_detected', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_domain'), 'targets', ['domain'], unique=True)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('schedule_interval', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_id'), 'scheduled_jobs', ['id'], unique=False)
    op.add_column('endpoints', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('secrets', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('subdomains', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'is_new')
    op.drop_column('subdomains', 'is_new')
    op.drop_column('secrets', 'is_new')
    op.drop_column('endpoints', 'is_new')
    op.drop_index(op.f('ix_scheduled_jobs_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_domain'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
